import { Cook, Dish, SubscriptionPlan, Order, CookPartnerRegistration } from './types';

// Mock In-Memory Database Store for KookIndia Marketplace

export const INITIAL_COOKS: Cook[] = [
  {
    id: 'cook-1',
    name: 'Sunita Sharma',
    kitchen_name: 'Sharma Ji Ki Rasoi',
    city: 'Bangalore',
    locality: 'Indiranagar',
    state: 'Karnataka',
    address: '12th Main Road, Indiranagar, Bangalore',
    fssai_license: '21223190004512',
    bio: 'PUNJABI HOME CHEF (15+ YRS). Cooking authentic North Indian home-style thalis, Rajma Chawal, and Sarson Ka Saag with pure Desi Ghee.',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    kitchen_image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    cuisine_specialties: ['North Indian', 'Punjabi', 'Thalis'],
    rating: 4.9,
    review_count: 142,
    is_verified: true,
    is_active: true,
    lead_time_hours: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cook-2',
    name: 'Meenakshi Sundaram',
    kitchen_name: 'Chettinad Amma Kitchen',
    city: 'Bangalore',
    locality: 'Koramangala',
    state: 'Karnataka',
    address: '5th Block, Koramangala, Bangalore',
    fssai_license: '21223190008899',
    bio: 'CHETTINAD & KERALA SPECIALIST. Authentic Karaikudi non-veg curries, appam, and traditional Kerala Sadhya cooked using freshly ground spices.',
    profile_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    kitchen_image: 'https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=800&q=80',
    cuisine_specialties: ['South Indian', 'Chettinad', 'Kerala'],
    rating: 4.8,
    review_count: 98,
    is_verified: true,
    is_active: true,
    lead_time_hours: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cook-3',
    name: 'Anupama Banerjee',
    kitchen_name: 'Banerjee Rannaghar',
    city: 'Gurgaon',
    locality: 'DLF Phase 4',
    state: 'Haryana',
    address: 'Galleria Market Road, DLF Phase 4, Gurgaon',
    fssai_license: '20822005001123',
    bio: 'BENGALI HOME CHEF. Specialized in Shorshe Ilish, Kosha Mangsho, Luchi Alur Dom, and Mishti Doi for Gurgaon IT professionals.',
    profile_image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    kitchen_image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=800&q=80',
    cuisine_specialties: ['Bengali', 'Fish & Seafood'],
    rating: 4.95,
    review_count: 210,
    is_verified: true,
    is_active: true,
    lead_time_hours: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cook-4',
    name: 'Bhavna Patel',
    kitchen_name: 'Patel Marwari & Gujarati Thali',
    city: 'Mumbai',
    locality: 'Ghatkopar West',
    state: 'Maharashtra',
    address: 'LBS Marg, Ghatkopar West, Mumbai',
    fssai_license: '21522012009944',
    bio: '100% PURE VEG & JAIN KITCHEN. Authentic Undhiyu, Gujarati Dal Dhokli, Bajra Roti, and Marwari Gatte Ki Sabzi cooked in peanut oil.',
    profile_image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80',
    kitchen_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    cuisine_specialties: ['Gujarati', 'Rajasthani', 'Pure Veg / Jain'],
    rating: 4.9,
    review_count: 175,
    is_verified: true,
    is_active: true,
    lead_time_hours: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cook-5',
    name: 'Begum Sultan Siddiqui',
    kitchen_name: 'Royal Nizami Handi',
    city: 'Hyderabad',
    locality: 'Banjara Hills',
    state: 'Telangana',
    address: 'Road No. 12, Banjara Hills, Hyderabad',
    fssai_license: '23623001004455',
    bio: 'HYDERABADI DUM BIRYANI & NIZAMI SPECIALIST. Slow-cooked Dum Biryani in clay pots using vintage family secret spices.',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    kitchen_image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    cuisine_specialties: ['North Indian', 'Biryani', 'Nizami'],
    rating: 4.88,
    review_count: 312,
    is_verified: true,
    is_active: true,
    lead_time_hours: 4,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_DISHES: Dish[] = [
  // Sunita Sharma (Punjabi - Bangalore)
  {
    id: 'dish-1',
    cook_id: 'cook-1',
    name: 'Special Amritsari Chole Bhature (2 Pcs)',
    description: 'Authentic 12-hour spiced chole served with 2 fluffy bhature, pickled chilles, onion salad, and mint chutney.',
    price: 189,
    image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    cuisine: 'North Indian',
    is_veg: true,
    is_jain: false,
    is_gluten_free: false,
    prep_time_minutes: 45,
    is_preorder_only: false,
    min_order_notice_hours: 1,
    serves_people: 1,
    daily_stock_limit: 30,
    stock_remaining: 18,
    is_available: true,
  },
  {
    id: 'dish-2',
    cook_id: 'cook-1',
    name: 'Homestyle Ghar Ki Thali (Veg)',
    description: '2 Ghee Phulkas, Steamed Basmati Rice, Dal Tadka, Paneer Butter Masala, Aloo Gobi, Raita, and Gulab Jamun.',
    price: 249,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    cuisine: 'North Indian',
    is_veg: true,
    is_jain: false,
    is_gluten_free: false,
    prep_time_minutes: 30,
    is_preorder_only: false,
    min_order_notice_hours: 1,
    serves_people: 1,
    daily_stock_limit: 40,
    stock_remaining: 24,
    is_available: true,
  },
  {
    id: 'dish-3',
    cook_id: 'cook-1',
    name: 'Desi Ghee Rajma Chawal Bowl',
    description: 'Slow-cooked Jammu rajma in rich onion-tomato gravy served with aromatic Jeera Rice and home-made pickle.',
    price: 179,
    image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    cuisine: 'North Indian',
    is_veg: true,
    is_jain: false,
    is_gluten_free: true,
    prep_time_minutes: 30,
    is_preorder_only: false,
    min_order_notice_hours: 1,
    serves_people: 1,
    daily_stock_limit: 35,
    stock_remaining: 15,
    is_available: true,
  },

  // Meenakshi Sundaram (Chettinad - Bangalore)
  {
    id: 'dish-4',
    cook_id: 'cook-2',
    name: 'Authentic Chettinad Chicken Curry & Kal Dosa',
    description: 'Spicy country chicken curry slow-cooked with roasted hand-ground spices, served with 3 soft Kal Dosas.',
    price: 279,
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    cuisine: 'South Indian',
    is_veg: false,
    is_jain: false,
    is_gluten_free: true,
    prep_time_minutes: 45,
    is_preorder_only: true,
    min_order_notice_hours: 2,
    serves_people: 1,
    daily_stock_limit: 25,
    stock_remaining: 10,
    is_available: true,
  },
  {
    id: 'dish-5',
    cook_id: 'cook-2',
    name: 'Traditional Kerala Fish Curry (Meen Curry)',
    description: 'Fresh Seer fish cooked in sour Kudampuli (Malabar tamarind) and coconut milk sauce, served with Red Matta Rice.',
    price: 320,
    image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    cuisine: 'South Indian',
    is_veg: false,
    is_jain: false,
    is_gluten_free: true,
    prep_time_minutes: 50,
    is_preorder_only: true,
    min_order_notice_hours: 3,
    serves_people: 1,
    daily_stock_limit: 20,
    stock_remaining: 8,
    is_available: true,
  },

  // Anupama Banerjee (Bengali - Gurgaon)
  {
    id: 'dish-6',
    cook_id: 'cook-3',
    name: 'Shorshe Ilish (Hilsa in Mustard Gravy) Meal',
    description: 'Fresh Hilsa fish steamed in yellow mustard paste and green chillies, served with Gobindobhog Rice and Jhuri Aloo Bhaja.',
    price: 490,
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Bengali',
    is_veg: false,
    is_jain: false,
    is_gluten_free: true,
    prep_time_minutes: 60,
    is_preorder_only: true,
    min_order_notice_hours: 3,
    serves_people: 1,
    daily_stock_limit: 15,
    stock_remaining: 5,
    is_available: true,
  },
  {
    id: 'dish-7',
    cook_id: 'cook-3',
    name: 'Kolkata Chicken Biryani (With Aloo & Egg)',
    description: 'Fragrant aromatic biryani with juicy chicken leg piece, boiled egg, and melt-in-mouth potato, cooked in Kolkata style.',
    price: 299,
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Bengali',
    is_veg: false,
    is_jain: false,
    is_gluten_free: true,
    prep_time_minutes: 45,
    is_preorder_only: false,
    min_order_notice_hours: 2,
    serves_people: 1,
    daily_stock_limit: 30,
    stock_remaining: 12,
    is_available: true,
  },

  // Bhavna Patel (Gujarati/Jain - Mumbai)
  {
    id: 'dish-8',
    cook_id: 'cook-4',
    name: 'Special Gujarati Executive Thali (Pure Veg)',
    description: 'Gujarati Sweet Kadi, Ringan No Oro, Sev Tameta Sabzi, 4 Fulka Roti, Steamed Rice, Khaman Dhokla, and Shrikhand.',
    price: 220,
    image_url: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80',
    cuisine: 'Gujarati',
    is_veg: true,
    is_jain: true,
    is_gluten_free: false,
    prep_time_minutes: 30,
    is_preorder_only: false,
    min_order_notice_hours: 1,
    serves_people: 1,
    daily_stock_limit: 50,
    stock_remaining: 28,
    is_available: true,
  },

  // Begum Sultan Siddiqui (Biryani - Hyderabad)
  {
    id: 'dish-9',
    cook_id: 'cook-5',
    name: 'Royal Hyderabadi Mutton Dum Biryani (Pot)',
    description: 'Handi Dum Biryani marinated in yogurt and saffron spices overnight, served with Mirchi Ka Salan and Burani Raita.',
    price: 380,
    image_url: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    cuisine: 'North Indian',
    is_veg: false,
    is_jain: false,
    is_gluten_free: true,
    prep_time_minutes: 60,
    is_preorder_only: true,
    min_order_notice_hours: 4,
    serves_people: 1,
    daily_stock_limit: 40,
    stock_remaining: 19,
    is_available: true,
  },
];

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'sub-1',
    cook_id: 'cook-1',
    cook_name: 'Sunita Sharma',
    kitchen_name: 'Sharma Ji Ki Rasoi',
    city: 'Bangalore',
    title: 'North Indian Executive Lunch Tiffin (Monthly)',
    description: 'Daily homestyle North Indian lunch delivered Mon-Fri. 4 Roti, 1 Paneer/Veg Curry, Dal Tadka, Rice, Raita & Pickle.',
    cuisine: 'North Indian',
    price_per_month: 3499,
    price_per_week: 999,
    price_per_meal: 140,
    meal_types: ['Lunch'],
    delivery_days: ['Mon-Fri (5 Days/wk)'],
    is_veg: true,
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'sub-2',
    cook_id: 'cook-4',
    cook_name: 'Bhavna Patel',
    kitchen_name: 'Patel Marwari & Gujarati Thali',
    city: 'Mumbai',
    title: 'Pure Veg / Jain Daily Dinner Tiffin',
    description: 'Wholesome Gujarati & Rajasthani pure veg dinner. 4 Rotis, 2 Sabzi, Dal-Rice, Farsan item & buttermilk.',
    cuisine: 'Gujarati / Jain',
    price_per_month: 3799,
    price_per_week: 1099,
    price_per_meal: 150,
    meal_types: ['Dinner'],
    delivery_days: ['Mon-Sat (6 Days/wk)'],
    is_veg: true,
    image_url: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'sub-3',
    cook_id: 'cook-3',
    cook_name: 'Anupama Banerjee',
    kitchen_name: 'Banerjee Rannaghar',
    city: 'Gurgaon',
    title: 'Authentic Bengali Office Lunch Subscription',
    description: 'Traditional Bengali lunch box with Fish/Chicken curry on alternating days, Bhaja, Dal, Roti & Rice.',
    cuisine: 'Bengali',
    price_per_month: 4499,
    price_per_week: 1299,
    price_per_meal: 180,
    meal_types: ['Lunch'],
    delivery_days: ['Mon-Fri (5 Days/wk)'],
    is_veg: false,
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'KI-88912',
    customer_name: 'Rahul Verma',
    customer_phone: '+91 98765 43210',
    customer_email: 'rahul.v@gmail.com',
    delivery_address: 'Flat 402, Sunshine Apartments, Indiranagar',
    city: 'Bangalore',
    locality: 'Indiranagar',
    cook_id: 'cook-1',
    cook_name: 'Sunita Sharma',
    kitchen_name: 'Sharma Ji Ki Rasoi',
    items: [
      { dish_id: 'dish-1', dish_name: 'Special Amritsari Chole Bhature (2 Pcs)', price: 189, quantity: 1 },
      { dish_id: 'dish-3', dish_name: 'Desi Ghee Rajma Chawal Bowl', price: 179, quantity: 1 },
    ],
    subtotal: 368,
    delivery_fee: 40,
    platform_fee: 15,
    total_amount: 423,
    payment_method: 'UPI',
    payment_status: 'PAID',
    order_status: 'COOKING',
    delivery_partner: 'Dunzo',
    created_at: new Date(Date.now() - 25 * 60000).toISOString(), // 25 mins ago
    estimated_delivery_time: '35-45 mins',
  },
];

// Helper Query Functions
export function getCooks(city?: string, cuisine?: string) {
  return INITIAL_COOKS.filter(c => {
    const matchesCity = !city || city === 'All' || c.city.toLowerCase() === city.toLowerCase();
    const matchesCuisine = !cuisine || cuisine === 'All' || c.cuisine_specialties.some(s => s.toLowerCase().includes(cuisine.toLowerCase()));
    return matchesCity && matchesCuisine;
  });
}

export function getCookById(id: string) {
  return INITIAL_COOKS.find(c => c.id === id) || null;
}

export function getDishesByCookId(cookId: string) {
  return INITIAL_DISHES.filter(d => d.cook_id === cookId);
}

export function getAllDishes(cuisine?: string, isVegOnly?: boolean) {
  return INITIAL_DISHES.filter(d => {
    const matchesCuisine = !cuisine || cuisine === 'All' || d.cuisine.toLowerCase() === cuisine.toLowerCase();
    const matchesVeg = !isVegOnly || d.is_veg === true;
    return matchesCuisine && matchesVeg;
  });
}

export function getSubscriptions(city?: string) {
  return INITIAL_SUBSCRIPTION_PLANS.filter(s => !city || city === 'All' || s.city.toLowerCase() === city.toLowerCase());
}
